Internal Server Error: /api/example/
Traceback (most recent call last):
  File "C:\Users\FakuPara\.virtualenvs\DjangoRestApi-HZ94RKMq\lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
  File "C:\Users\FakuPara\.virtualenvs\DjangoRestApi-HZ94RKMq\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\FakuPara\.virtualenvs\DjangoRestApi-HZ94RKMq\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\Users\FakuPara\.virtualenvs\DjangoRestApi-HZ94RKMq\lib\site-packages\rest_framework\response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "C:\Users\FakuPara\.virtualenvs\DjangoRestApi-HZ94RKMq\lib\site-packages\rest_framework\renderers.py", line 722, in render
    template = loader.get_template(self.template)
  File "C:\Users\FakuPara\.virtualenvs\DjangoRestApi-HZ94RKMq\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: rest_framework/api.html
"GET /api/example/ HTTP/1.1" 500 145
Internal Server Error: /api/example/
Traceback (most recent call last):
  File "C:\Users\FakuPara\.virtualenvs\DjangoRestApi-HZ94RKMq\lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
  File "C:\Users\FakuPara\.virtualenvs\DjangoRestApi-HZ94RKMq\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\FakuPara\.virtualenvs\DjangoRestApi-HZ94RKMq\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\Users\FakuPara\.virtualenvs\DjangoRestApi-HZ94RKMq\lib\site-packages\rest_framework\response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "C:\Users\FakuPara\.virtualenvs\DjangoRestApi-HZ94RKMq\lib\site-packages\rest_framework\renderers.py", line 722, in render
    template = loader.get_template(self.template)
  File "C:\Users\FakuPara\.virtualenvs\DjangoRestApi-HZ94RKMq\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: rest_framework/api.html
"GET /api/example/ HTTP/1.1" 500 145
Internal Server Error: /api/example/
Traceback (most recent call last):
  File "C:\Users\FakuPara\.virtualenvs\DjangoRestApi-HZ94RKMq\lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
  File "C:\Users\FakuPara\.virtualenvs\DjangoRestApi-HZ94RKMq\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\FakuPara\.virtualenvs\DjangoRestApi-HZ94RKMq\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\Users\FakuPara\.virtualenvs\DjangoRestApi-HZ94RKMq\lib\site-packages\rest_framework\response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "C:\Users\FakuPara\.virtualenvs\DjangoRestApi-HZ94RKMq\lib\site-packages\rest_framework\renderers.py", line 722, in render
    template = loader.get_template(self.template)
  File "C:\Users\FakuPara\.virtualenvs\DjangoRestApi-HZ94RKMq\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: rest_framework/api.html
"GET /api/example/ HTTP/1.1" 500 145
Not Found: /api/example/rest_framework/css/bootstrap.min.css
"GET /api/example/rest_framework/css/bootstrap.min.css HTTP/1.1" 404 179
Not Found: /api/example/rest_framework/css/bootstrap-tweaks.css
"GET /api/example/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 404 179
Not Found: /api/example/rest_framework/css/prettify.css
Not Found: /api/example/rest_framework/css/default.css
Not Found: /api/example/rest_framework/js/jquery-3.5.1.min.js
Not Found: /api/example/rest_framework/js/ajax-form.js
"GET /api/example/rest_framework/css/prettify.css HTTP/1.1" 404 179
"GET /api/example/rest_framework/js/jquery-3.5.1.min.js HTTP/1.1" 404 179
"GET /api/example/rest_framework/css/default.css HTTP/1.1" 404 179
Not Found: /api/example/rest_framework/js/csrf.js
"GET /api/example/rest_framework/js/ajax-form.js HTTP/1.1" 404 179
"GET /api/example/rest_framework/js/csrf.js HTTP/1.1" 404 179
Not Found: /api/example/rest_framework/js/bootstrap.min.js
"GET /api/example/rest_framework/js/bootstrap.min.js HTTP/1.1" 404 179
Not Found: /api/example/rest_framework/js/prettify-min.js
Not Found: /api/example/rest_framework/js/default.js
"GET /api/example/rest_framework/js/prettify-min.js HTTP/1.1" 404 179
"GET /api/example/rest_framework/js/default.js HTTP/1.1" 404 179
Internal Server Error: /api/example/
Traceback (most recent call last):
  File "C:\Users\FakuPara\.virtualenvs\DjangoRestApi-HZ94RKMq\lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
  File "C:\Users\FakuPara\.virtualenvs\DjangoRestApi-HZ94RKMq\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\FakuPara\.virtualenvs\DjangoRestApi-HZ94RKMq\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\Users\FakuPara\.virtualenvs\DjangoRestApi-HZ94RKMq\lib\site-packages\rest_framework\response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "C:\Users\FakuPara\.virtualenvs\DjangoRestApi-HZ94RKMq\lib\site-packages\rest_framework\renderers.py", line 722, in render
    template = loader.get_template(self.template)
  File "C:\Users\FakuPara\.virtualenvs\DjangoRestApi-HZ94RKMq\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: rest_framework/api.html
"GET /api/example/ HTTP/1.1" 500 145
Not Found: /api/example/
"GET /api/example/ HTTP/1.1" 404 179
Not Found: /api/example/list
"GET /api/example/list HTTP/1.1" 404 179
Not Found: /api
"GET /api HTTP/1.1" 404 179
Not Found: /api/example/
"GET /api/example/ HTTP/1.1" 404 179
Not Found: /api/example/
"GET /api/example/ HTTP/1.1" 404 179
Not Found: /api
"GET /api HTTP/1.1" 404 179
Not Found: /api/LIST
"GET /api/LIST HTTP/1.1" 404 179
Not Found: /api/LIST
"GET /api/LIST HTTP/1.1" 404 179
Not Found: /api
"GET /api HTTP/1.1" 404 179
Not Found: /api
"GET /api HTTP/1.1" 404 179
Not Found: /api
"GET /api HTTP/1.1" 404 179
Not Found: /api
"GET /api HTTP/1.1" 404 179
Not Found: /api
"GET /api HTTP/1.1" 404 179
Not Found: /api
"GET /api HTTP/1.1" 404 179
Not Found: /api
"GET /api HTTP/1.1" 404 179
Not Found: /api/
"GET /api/ HTTP/1.1" 404 179
Not Found: /api/
"GET /api/ HTTP/1.1" 404 179
Not Found: /api/
"GET /api/ HTTP/1.1" 404 179
Not Found: /api/
"GET /api/ HTTP/1.1" 404 179
Not Found: /api/
"GET /api/ HTTP/1.1" 404 179
Not Found: /api/
"GET /api/ HTTP/1.1" 404 179
Not Found: /api
"GET /api HTTP/1.1" 404 179
Not Found: /api/
"GET /api/ HTTP/1.1" 404 179
Not Found: /api
"GET /api HTTP/1.1" 404 179
Bad Request: /api/pv_yield
"GET /api/pv_yield HTTP/1.1" 400 56
Not Found: /api/pv_yield
"GET /api/pv_yield?state=germany HTTP/1.1" 404 37
Not Found: /api/pv_yield
"GET /api/pv_yield?state=california HTTP/1.1" 404 37
Internal Server Error: /api/pv_yield
Traceback (most recent call last):
  File "C:\Users\FakuPara\.virtualenvs\DjangoRestApi-HZ94RKMq\lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
  File "C:\Users\FakuPara\.virtualenvs\DjangoRestApi-HZ94RKMq\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\FakuPara\.virtualenvs\DjangoRestApi-HZ94RKMq\lib\site-packages\django\views\decorators\csrf.py", line 55, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\FakuPara\.virtualenvs\DjangoRestApi-HZ94RKMq\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\FakuPara\.virtualenvs\DjangoRestApi-HZ94RKMq\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\FakuPara\.virtualenvs\DjangoRestApi-HZ94RKMq\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\FakuPara\.virtualenvs\DjangoRestApi-HZ94RKMq\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\FakuPara\.virtualenvs\DjangoRestApi-HZ94RKMq\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "E:\Programming\CodeChallange\DjangoRestApi\simple_REST_API\pvYields\views.py", line 28, in retrieve
    return Response(serializer.data.yield_value)
AttributeError: 'ReturnDict' object has no attribute 'yield_value'
"GET /api/pv_yield?state=California HTTP/1.1" 500 145
